- .github/workflows/R-CMD-check.yml
- .github/workflows/lintr.yaml
> fix_workflows: fix them

- .github/workflows/lintr.yaml
> fix_lintr_workflow: use lintr version from renv.lock

- .github/workflows/pkgdown.yml
Use common pkgdown workflow from the template.
> Fix pkgdown workflow

- .github/workflows/pkgdown.yml
This branch will be used by testers.
> Display docs on test branch

- NEWS.md
> add_news: add NEWS.md

- _pkgdown.yml
> update_pkgdown: use bootstrap 5 and add search

- renv.lock
> fix_website: try to update renv.lock

- .github/workflows/pkgdown.yml
> fix_website: update pkgdown workflow

- .github/workflows/pkgdown.yml
> default_page: set default to test

- vignettes/adtte.Rmd
> closes #97 include lubridate

- .Rbuildignore
- .lycheeignore
- DESCRIPTION
- R/derive_param_clinbenefit.R
- R/derive_param_confirmed_bor.R
- R/derive_param_confirmed_resp.R
- _pkgdown.yml
- man/derive_param_clinbenefit.Rd
- man/derive_param_confirmed_bor.Rd
- man/derive_param_confirmed_resp.Rd
- renv.lock
> closes #82 anl01fl examples@devel

- .github/workflows/common.yml
Use CI/CD workflows from admiralci: https://github.com/pharmaverse/admiralci
> Use admiralci workflows

- R/derive_param_bor.R
- R/derive_param_confirmed_bor.R
- man/derive_param_bor.Rd
- man/derive_param_confirmed_bor.Rd
> closes #83 - clarify ref_start_window description

- inst/templates/ad_adrs.R
- vignettes/adrs.Rmd
> closes #73 partial date@devel

- inst/templates/ad_adrs.R
- vignettes/adrs.Rmd
> closes 79 update adrs vignette obs number@devel

- inst/templates/ad_adrs.R
- vignettes/adrs.Rmd
> closes #110 closes #115 adrs enhance@devel

- vignettes/adtte.Rmd
> closes #112 added extra example for AVAL in months

- DESCRIPTION
- man/admiralonco-package.Rd
> Closes #155 155_CRAN_comments: update DESCRIPTION

- README.md
> fix_badges

- README.md
Added the pharmaverse badge now that this package extension is live on the site.
The following line …
> update pharmaverse badge

- _pkgdown.yml
_pkgdown.yml program updated : cran date from false to true & correct indention of 'news'
Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of …
> closes #160_crandate updated

- NEWS.md
- inst/WORDLIST
- inst/templates/ad_adrs.R
- inst/templates/ad_adtte.R
> closes #177 rds@devel

- DESCRIPTION
- LICENSE.md
- man/admiralonco-package.Rd
> Closes #173 add bms to license

- .github/workflows/common.yml
- .lycheeignore
- README.Rmd
- vignettes/admiralonco.Rmd
- vignettes/adrs.Rmd
- vignettes/adtte.Rmd
> closes #171 multiversion@devel

- NEWS.md
- inst/templates/ad_adtte.R
- vignettes/adtte.Rmd
> closes #203 adtte clean ups in line with admiral

- DESCRIPTION
- NEWS.md
- man/admiralonco-package.Rd
> Closes #211 bug_link: add "Report a Bug" link

- NEWS.md
- README.Rmd
- README.md
> #223 dependencies: add dependencies section

- DESCRIPTION
Remove the styler from dependencies https://github.com/pharmaverse/admiral/issues/1919
/roxygenize
> Update DESCRIPTION and remove styler

- NEWS.md
- inst/templates/ad_adrs_basic.R
- vignettes/adrs_basic.Rmd
> Closes #245 fix_crsp: Update CRSP derivation in vignette and template

- .github/workflows/common.yml
- DESCRIPTION
- NEWS.md
> update version number

- DESCRIPTION
- R/derive_param_response.R
- staged_dependencies.yaml
- vignettes/nactdt.Rmd
…ge to DESCRIPTION file
Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged …
> Request to close issue #246

- DESCRIPTION
- NEWS.md
- _pkgdown.yml
- man/admiralonco-package.Rd
Closes #262 
Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the …
> #262 update to website (buttons)

- DESCRIPTION
- R/check_crpr.R
- man/admiralonco-package.Rd
- man/get_crpr_dataset.Rd
> address CRAN feedback

- NEWS.md
- README.md
- inst/templates/ad_adrs.R
- inst/templates/ad_adrs_basic.R
- inst/templates/ad_adtr.R
- inst/templates/ad_adtte.R
- vignettes/admiralonco.Rmd
- vignettes/adrs.Rmd
- vignettes/adrs_basic.Rmd
- vignettes/adtr.Rmd
- vignettes/adtte.Rmd
- vignettes/irecist.Rmd
- vignettes/nactdt.Rmd
> closes #281 closes #284 subject keys and slack link

- LICENSE.md
- README.md
> closes #287 replace non ascii characters

- DESCRIPTION
- NEWS.md
> Closes #290 release_110: Release 1.1.0

- NEWS.md
- R/tte_sources.R
- man/tte_source_objects.Rd
> Closes #293 fix_tte_source: fix documentation of TTE source objects

- DESCRIPTION
- NEWS.md
> Closes #300 release_1_2: update version

- vignettes/adrs_imwg.Rmd
> Closes #300 release_1_2: update link

- NEWS.md
- vignettes/adtr.Rmd
> Closes #305 display_anl01fl: display ANL01FL and fix typo
